### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by dataod** [zilexa/UbuntuBudgie-config#1]
Hi, 
I ran the script on fresh 20.04LTS VM and loading time went from a snappy couple seconds to a few minutes. What could be causing it? Do you experience increase in loading times?

I did change the root partition from ext4 to btrfs on install.

**Comment by zilexa** [comment]
Hi, just to inform you I switched to Manjaro (Gnome), stopped using Ubuntu (Budgie).

Budgie doesn't support modern laptops. Support for screens with high resolution is broken and won't be fixed anytime soon. There were also other issues that are simply not easily fixed for the UB team.

Manjaro supports the latest stable Linux kernel and firmware --> this is necessary to have a working modern laptop. Can't wait half a year or longer for a major Ubuntu release to get a prpery working chipset, audio or video. Ofcourse you can install the latest kernel on Ubuntu, but that's manual work, prone to making mistakes and ruining your system.

Manjaro provides a MUCH better out of the box experience. Also, there is no need to fiddle with the command line when you need to install applications: it's App Store is far superior, supporting most applications from its repository without the need for slow Snap. On top of that, AUR is supported which means literally all applications can be installed and auto updated. Ubuntu has nothing that comes close.

Add to that the fact that Manjaro doesn't do major releases, no need to do a clean install and you have a winner. It also uses less RAM.

My post install is practically finished (and tested) and better documented:
https://github.com/zilexa/manjaro-gnome-post-install

**Comment by dataod** [comment]
> 
> 
> Hi, just to inform you I switched to Manjaro (Gnome), stopped using Ubuntu (Budgie).
> 
> Budgie doesn't support modern laptops. Support for screens with high resolution is broken and won't be fixed anytime soon. There were also other issues that are simply not easily fixed for the UB team.
> 
> Manjaro supports the latest stable Linux kernel and firmware --> this is necessary to have a working modern laptop. Can't wait half a year or longer for a major Ubuntu release to get a prpery working chipset, audio or video. Ofcourse you can install the latest kernel on Ubuntu, but that's manual work, prone to making mistakes and ruining your system.
> 
> Manjaro provides a MUCH better out of the box experience. Also, there is no need to fiddle with the command line when you need to install applications: it's App Store is far superior, supporting most applications from its repository without the need for slow Snap. On top of that, AUR is supported which means literally all applications can be installed and auto updated. Ubuntu has nothing that comes close.
> 
> Add to that the fact that Manjaro doesn't do major releases, no need to do a clean install and you have a winner. It also uses less RAM.
> 
> My post install is practically finished (and tested) and better documented: https://github.com/zilexa/manjaro-gnome-post-install

:) Interesting coincidence. I switched to Manjaro myself since that inquiry, but to KDE-plasma flavor.
